:width: 100%
:revealjs_margin: '0.1'
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]
= Groovy After All These Years


[data-background={imagesdir}/TitleSlide-GroovyAfterAllTheseYears.jpg]
== !


== About Me
:hardbreaks:

Scott Hickey +
Principal Enterprise Architect +
Mutual of Omaha


@jshickey +
scott.hickey@mutualofomaha.com +
https://github.com/jshickey/SpringOne2GX-2015

:!hardbreaks:

== Agenda
_(please ask questions as you have them)_

[%step]
* Lessons Learned
* Project Overview
* Code Examples
// * TDD
// * Decision Points
// * Lessons Learned Getting Into Production
// * Eight Years of Enhancements and Maintainence
* Other Groovy Sightings at Mutual of Omaha


== After Seven Years in Production We Learned Groovy is Better, Period.
[%step]
* Concise
* Easier to read and comprehend
* Easier to on-board new devs (experienced and novice)
* Easier to maintain/extend/troubleshoot
* Non-Java devs who know the business can write/maintain code

=== After Seven Years in Production We Learned Groovy is Better, Period.
[%step]
* Use it on the code that is hardest to understand, changes the most, most susceptible to logic errors
* Development Speed
* Fast time to market for new apps
* Quick to enhance app with new features
* TDD - you’ll always be writing meaningful tests!


== Project Overview
Ten years ago, we started a project to build new group insurance sales system that...

* integrates the functions of 7 separate legacy systems
* using modern technology (Java)
* allow the actuaries to maintain the rating code

[NOTE.speaker]
--
How to reconcile 2 & 3 weren't known
--

=== Sales System Components
[%step]
* Contact management
* Proposals
* Group Census
* Plan Design
* Compute Premium => _Rating Engine_
* Proposal Generation
* Enrollment Documentation

[NOTE.speaker]
--
* rating engine one part of bigger process
* hardest part of hard project
* xxx Global Svcs wouldn't touch it
--

=== Project Business Goals
[%step]
* Time to Market for New Product Features
  ** can't make CR process worse
  ** cont. change to hardest part of the system

* Improve Cycle Time in Sales Process
  ** avoid duplication of effort
  ** near instantaneous rate computation

[NOTE.speaker]
--
* six months to implement product feature
  ** elminate requirements specification
  ** easy to change code
* performance matters
--


=== Project Facts

[%step]
* Project Started 2005
* Muliyear, Multi-million dollar project, large project team
* High visibility app for a Fortune 500 Company
* Front End written with Eclipse Rich Client Platform
* Backend traditional WebSphere, Hibernate J2EE

=== Rating Engine Team
Developed by a team of 8

* 1 Project Manager
* 3 Members of the Group Actuarial Staff
* 4 I/S Developers
* Extremely Limited Java Experience
** 1 Seasoned Java Developer
** 1 developer with some Java experience
** 5 with No Actual Java development experience

=== Rating Engine Tools

* Started with Groovy: pre 1.0
* Ant
* JEdit
* Comand Line Dubugger
* Eventually Eclipse

=== Application Architecture
Rich Client ->

J2EE App Server

* controller
* services
* business logic => _rating engine_
* DAO

// TODO: add a diagram here

=== Why Groovy?
[%step]
* Maintenance by IT and Subject Matter Experts
** Readability for complicated business logic
** Minimal syntax - signal/noise ratio
** Decimal math for accuracy
* Seamless Java Integration


=== Deployed to Production in 2008

* Working Rating Engine
* A Versatile Test Harness
* 45,000 lines of Code
* Avg time to rate/price was 3 to 4 seconds (Groovy engine rates 99.9% of the groups in less than 1 second)

[NOTE.speaker]
--
99.9% of the calcs could be performed in less than one second - with the very old version of groovy.

The system was computing 200,000 - 300,000 rate multipliers per request.
--


=== Since 2008
* Other Developers have come and gone
* 5 additional Group Actuarial individuals have been or are active in the code
* 7 additional I/S Developers have been or are active in the code base
* Only 2 of these 12 had significant Java experience prior to supporting the Rating Engine

=== Since 2008 (cont.)
* The Code base has Grown Significantly
* Added 3 New Products (and more on the way)
* Re-architected the calculations for almost every product
* Now at 120,000 Lines of Code
* Developed an Entire New Reporting Process in Groovy
* Ported from DB2 to Teradata

=== Run Time Errors
[%step]
.Run Time Errors are a Concern
* We’ve had less than 10 instances in prod
* They can be costly and embarrassing

[%step]
.BUT Not as big a concern as failing silently!
* Calculation errors
* Calculation omissions
* Requirements misunderstandings


== Code Examples
* Groovy
** Groovy Beans
** Collection Classes
** Big Decimal
* Spring
** Dependency Injection - Testing
** AOP - Exception Handling & Troubleshooting
** Stateless Singletons (Functional Design)

[NOTE.speaker]
--
Beans - dot property notation, implied getters/setters, maps
Collections/Operator Overloading - was our DSL
--


=== Functions With Maps & Beans
//[width='100%']
[source,groovy]
----
import java.time.*
class Person {
     String fname
     String lname
     LocalDate dob
}
age = {Period.between( it.dob, LocalDate.now())}
p = new Person(fname:'Scott',
               lname:'Hickey',
               dob:LocalDate.of(1963,Month.SEPTEMBER,30))
age(p).dump()
===> <java.time.Period@d0b33 years=51 months=11 days=13>

age(p) == age([dob:LocalDate.of(1963,Month.SEPTEMBER,30)])
===> true
----

[NOTE.speaker]
--
* only code get/set that does something interesting
* starting coding functions first, model later
--
=== Business DSL for Free

[source,groovy]
----
products.each { product ->
  product.options.each { optionName, optionValue->
    people.each { person ->
      def factor = lookupFactor(person.age, optionName, optionValue)
      person.optionFactor **= factor
    }
  }
}
----
////
import java.time.*
class Person {
    String first
    String last
    LocalDate dob
}
age = {Period.between( it.dob, LocalDate.now())}
p = new Person(first:'Scott',last:'Hickey',dob:LocalDate.of( 1963, Month.SEPTEMBER, 30))
age(p).dump()
age([dob:LocalDate.of( 1963, Month.SEPTEMBER, 30)]).dump()

////

=== Manipulating Collections

// TODO: better code example


[source,language="groovy"]
----
static void sortDemos(claims) {
  claims.sort{it.lName}
  claims.sort{it.amount}
  claims = claims.reverse()
  claims = claims.sort{it.fName}.reverse()
}

static void sumDemos(claims) {
  def totClaims = claims.sum{it.amount}
  def claimsUnder30000 = claims.findAll {
    it.amount < 30000.00
  }.sum{ it.amount }

  def avgClaim = claims.sum{it.amount} / claims.size()
}
----


=== Readability - Process

[source,language="groovy"]
----
def createProductOutput(productInput) {
    def productOutput = new ProductOutput()
    def planFactors = []
    productInput.planDesigns.each{ pd ->
        def planCensus = productInput.planDesignCensusMap
                                .get(pd.planDesignId)
        def members = generatePlanMembers(planCensus)
        calculateMemberFactors(members)
        def planFactor = generatePlanFactors(members)
        planFactors << planFactor
        calculateExpenses(planFactor, members)
    }
    planFactors << generateAlternateFactor(planFactors)
}
----

[NOTE.speaker]
--
* nothing feels like Java
* could you express this with less syntax?
--


=== Readability - Calcs

[source,language="groovy"]
----
billingClaimCost = premium - (
    typeAmt +
    typePerEe +
    typePctCc +
    comsData.comsAmt +
    ( comsData.comsPepm * planDesigns[0].altPartLivesAmt * 12 ) +
    type2Flat +
    miscExp)

members.each { member ->
    member.eeDisClm = member.eeVol *
                      member.factor1 *
                      planFactor.factorA *
                      planFactor.factorB *
                      planFactor.factorC *
                      member.factor2 * member.factor3
}
----
[NOTE.speaker]
--
* Pepm - Per employee Per month
* means something to actuaries, minimal syntax
--

=== Java BigDecimal Math Example
[%step]
* (d * (b - c) + e * (c - a)) / (a -b)

[source,java]
----
BigDecimal interpolate(final BigDecimal lowerBound,
  final BigDecimal upperBound, final BigDecimal value,
  final BigDecimal lowerValue, final BigDecimal upperValue) {

  final BigDecimal uMinusv = upperBound.subtract(value);
  final BigDecimal vMinusl = value.subtract(lowerBound);
  final BigDecimal uMinusl = upperBound.subtract(lowerBound);

  return lowerValue.multiply(uMinusv)
                   .add(upperValue.multiply(vMinusl))
                   .divide(uMinusl, 10, BigDecimal.ROUND_HALF_UP);
}
----

=== Groovy BigDecimal Math Example

* operating overloading
* BigDecimal literals by default
* auto-coerces Integers to BigDecimal

[source,groovy]
----
def interpolate(lowerBound, upperBound, value,
                 lowerValue, upperValue) {

    (lowerValue * (upperBound - value) +
     upperValue * (value - lowerBound)) /
    (upperBound - lowerBound)

}
----

=== Get the Right Behavior by Default
----
groovy:000> def interpolate(lowerBound, upperBound, value,
groovy:001>                 lowerValue, upperValue) {
groovy:002>
groovy:002>  (lowerValue * (upperBound - value) +
groovy:003>   upperValue * (value - lowerBound)) /
groovy:004>  (upperBound - lowerBound)
groovy:005>
groovy:005> }
===> true
groovy:000> interpolate(20, 30, 25, 1.5, 2.5)
===> 2.0
groovy:000> interpolate(20, 30, 25, 1.5, 2.5).dump()
===> <java.math.BigDecimal@26d intVal=20 scale=1 precision=2 stringCache=null intCompact=20>
----


=== BigDecimal - Accuracy

Don't want to introduce errors accidentally by using floats or doubles +
=> when multiplying factors together

[source,groovy]
----
members.each { member ->
  member.eeDisClm = member.eeVol * member.factor1 *
                    planFactor.factorA *
                    planFactor.factorB *
                    planFactor.factorC *
                    member.factor2 * member.factor3
}
----

=== BigDecimal - Accuracy (cont.)

Don't want to introduce errors accidentally by using floats or doubles  +
=> when looking up values in a rate table
----
groovy> println 1.1 + 0.1 == 1.2
true
groovy> println 1.1f + 0.1f == 1.2
false
groovy> println 1.1f + 0.1f
1.200000025331974

groovy> println 1.0 + 0.1 == 1.1
true
groovy> println 1.0f + 0.1f
1.1000000014901161
groovy> println 0.9f + 0.1f
0.9999999776482582
----


=== Spring Dependency Injection - Testing
50+ Lookup Tables Stored in Memory

.dental_sic.txt
----
rateSicCode, divCode, factor
      1,       1,      0.90
      1,       2,      1.00
      1,       3,      1.10
      2,       1,      0.93

----
.generates Groovy Map
----
rateTables = [ 'dental_sic': ['1-1' : 0.90,
                              '1-2' : 1.00,
                              '1-3' : 1.10,
                              '2-1' : 0.93]
----
=== Lazy Load Tables for Testing
At application startup, loading all of the rate tables involves:

* read and parse text file
* lookup and execute key-generation alogrithm for each row, in each table
* store the key and BigDecimal factor for each row, in each table

Using a Spring test profile to lazy load the tables saved 30-40 seconds when running a single unit test.

=== Exceptions Before Spring AOP
.Application Code (for every public api)
[source,groovy]
----
try {
   // this is the only like the business people care about
   rateBundle = rateCalc.createRateBundle(products, people)
   if (serializeFlag) {
      serializeInputs(products, people)
   }
} catch (RatingException e) {
   if (!supressSerialization) {
      serializeInputs(products, people)
   }
   throw e
} catch (Exception e) {
   if (!supressSerialization) {
      serializeInputs(products, people)
   }
   e.printStackTrace()
   throw new RatingException(e.getMessage())
}
----

=== Exceptions After Spring AOP
.Application Code
[source,groovy]
----
rateBundle = rateCalc.createRateBundle(products, people)
----

.Spring Config
[source,xml]
----
<!-- spring context file business people never see this-->
<aop:config proxy-target-class="true">
  <aop:pointcut id="ratingEnginePointcut"
    expression="execution(* rating.svc.RatingEngine.*(..))"/>
  <aop:aspect id="serializerBefore" ref="serializer">
    <aop:before pointcut-ref="ratingEnginePointcut" method="before"/>
  </aop:aspect>
  <aop:aspect id="serializerException" ref="serializer">
    <aop:after-throwing pointcut-ref="ratingEnginePointcut"
     throwing="exception"
     method="exceptionThrown"/>
  </aop:aspect>
</aop:config>
----
=== Spring Singletons, All Stateless
[source,groovy]
----
class LtdRateCalc extends DisabilityRateCalc implements RateCalc {

  private final Logger logger = Logger.getLogger("com.mutualofomaha.gsa.gap.rating.calc.ltd.LtdRateCalc")
  def censusUtils       // Configured in Spring context.xml
  def dateUtils       // Configured in Spring context.xml
  def factorTableService    // Configured in Spring context.xml
  def messageUtils      // Configured in Spring context.xml
  def ltdSeriatimCalc     // Configured in Spring context.xml
  def ltdMemberLevelCalc    // Configured in Spring context.xml
  def ltdExpenses       // Configured in Spring context.xml
  def ltdPlanLevelCalc    // Configured in Spring context.xml
  def ltdBaseRates      // Configured in Spring context.xml
  def ratingEngineController  // Configured in Spring context.xml
  def bankCalcUtils     // Configured in Spring context.xml

  public SeriatimBundle createSeriatimBundle(List planDesigns, Map planDesignCensusMap, Map factorTableVersionMap){
----

== Other Groovy Sightings
.*80+ Grails apps*
* used to replace internal Lotus Notes applications
* better option for scaling an internal app that get traction vs MS Access, Notes

.*Gradle*
* new Continuous Integration Platform for all JVM apps
* Custom Jenkins Job DSL for build pipeline

=== Gradle Example
.Creates Jenkins Build Pipeline
[source,gradle]
----
pipelineConfig {
  asi = 'ESC'
  projectName = 'CIP-SpringBootSimple'
  svnUrl = 'svn+ssh://svn/data/svn/MainRepository/Insurance/ESC/Utilities/trunk/CIP-SpringBootSimple'
  buildPipelineRows = 5
  notifiedUsers = ['req48764']
  authorizedUsers = ['req69111','req84082','req88320', 'req88551']

  createPipeline {
    initJob(gradleSwitches:'-is')
    buildAndUnitTestJob(skipTests: true)
    staticCodeAnalysisJob(gradleTasks: 'sonarRunner')
    publishSnapshotJob(gradleTasks:'war artifactoryPublish')
    promoteToReleaseCandidateJob()
    promoteToReleaseJob()
  }
}
----
[data-background={imagesdir}/Jenkins-Screenshot.png]
=== !

== Big Takeaways
:hardbreaks:
*Don’t Let FUD Get in Your Way*
Groovy is fast enough
Groovy is stable enough
Tooling is good enough
Awesome community and commercial support

*Benefits*
Groovy is accessible for all skill levels
Groovy is readable, concise
Groovy is powerful
*Groovy is phenomenal language for complicated business applications!*

:!hardbreaks:

////
== Blank screen

You can press `*b*` or `*.*` to blank your current screen.

Hit it again to bring it back.

== Overview

Press the `*esc*` key to get an overview of your slides.

== Including documents from subdir

.include::subdir/_b.adoc[]

include::subdir/_b.adoc[]


== build.gradle

[source,groovy]
----
include::{build-gradle}[]
----
////
